//! OPC DA quality types and conversions.

use std::fmt;

/// Major OPC DA quality status (bits 6-7, mask `0xC0`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum QualityMajor {
    /// The value is good and can be trusted (`0xC0`).
    #[default]
    Good,
    /// The quality of the value is uncertain, but may be usable (`0x40`).
    Uncertain,
    /// The value is bad and unusable (`0x00`).
    Bad,
}

/// Limit status for an OPC DA quality word (bits 0-1, mask `0x03`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum QualityLimit {
    /// The value is free to move in both directions (`0x00`).
    #[default]
    NotLimited,
    /// The value has reached its lower operational limit and cannot decrease further (`0x01`).
    LowLimited,
    /// The value has reached its upper operational limit and cannot increase further (`0x02`).
    HighLimited,
    /// The value is constant and cannot change (`0x03`).
    Constant,
}

/// Detailed substatus for an OPC DA quality word (bits 2-5, mask `0x3C`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum QualitySubstatus {
    /// No specific substatus information available (`0x00`).
    #[default]
    NonSpecific,
    /// The configuration of the server or item is invalid (`0x04`).
    ConfigurationError,
    /// The item address or identity is not connected to a data source (`0x08`).
    NotConnected,
    /// The device failure has prevented data acquisition (`0x0C`).
    DeviceFailure,
    /// A sensor or transducer failure was detected (`0x10`).
    SensorFailure,
    /// Communication with the underlying device or PLC has failed (`0x18`).
    CommFailure,
    /// The communication channel or device is out of service (`0x1C`).
    OutOfService,
    /// The value was generated by a last-known-value holding routine (`0x14`).
    LastUsableValue,
    /// The sensor was calibrated or adjusted and is currently unverified (`0x20`).
    SensorCalibrating,
    /// The acquired value has exceeded the configured Engineering Units (EGU) limits (`0x14` / `0x20`).
    EguExceeded,
    /// Multiple data sources disagreed, or subnormal values were averaged (`0x24`).
    SubNormal,
    /// The value has been overridden locally by an operator or manual simulation (`0x18`).
    LocalOverride,
}

/// Strongly-typed 16-bit OPC DA quality word.
///
/// Decomposes the raw 16-bit OPC DA quality field into:
/// - **Major** (bits 6-7): `Good` (`0xC0`), `Uncertain` (`0x40`), `Bad` (`0x00`).
/// - **Substatus** (bits 2-5): Detailed reason (e.g. `CommFailure`, `OutOfService`, `EguExceeded`).
/// - **Limit** (bits 0-1): Limit status (e.g. `LowLimited`, `HighLimited`, `Constant`).
/// - **Raw** (`u16`): The complete 16-bit quality word received from the OPC server.
///
/// # Examples
///
/// ```
/// use opc_da_client::{OpcQuality, QualityMajor, QualitySubstatus};
///
/// let quality = OpcQuality::from(0x00C0);
/// assert!(quality.is_good());
/// assert_eq!(quality.major(), QualityMajor::Good);
/// assert_eq!(quality.substatus(), QualitySubstatus::NonSpecific);
/// assert_eq!(quality.to_string(), "Good");
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct OpcQuality {
    major: QualityMajor,
    substatus: QualitySubstatus,
    limit: QualityLimit,
    raw: u16,
}

impl OpcQuality {
    /// Constructs an `OpcQuality` from individual components, synthesizing the 16-bit raw quality word.
    #[must_use]
    pub const fn new(
        major: QualityMajor,
        substatus: QualitySubstatus,
        limit: QualityLimit,
    ) -> Self {
        let major_raw: u16 = match major {
            QualityMajor::Good => 0x00C0,
            QualityMajor::Uncertain => 0x0040,
            QualityMajor::Bad => 0x0000,
        };

        let limit_raw: u16 = match limit {
            QualityLimit::NotLimited => 0x0000,
            QualityLimit::LowLimited => 0x0001,
            QualityLimit::HighLimited => 0x0002,
            QualityLimit::Constant => 0x0003,
        };

        #[allow(clippy::match_same_arms)]
        let substatus_raw: u16 = match (major, substatus) {
            (QualityMajor::Bad, QualitySubstatus::ConfigurationError) => 0x0004,
            (QualityMajor::Bad, QualitySubstatus::NotConnected) => 0x0008,
            (QualityMajor::Bad, QualitySubstatus::DeviceFailure) => 0x000C,
            (QualityMajor::Bad, QualitySubstatus::SensorFailure) => 0x0010,
            (QualityMajor::Bad, QualitySubstatus::LastUsableValue) => 0x0014,
            (QualityMajor::Bad, QualitySubstatus::CommFailure) => 0x0018,
            (QualityMajor::Bad, QualitySubstatus::OutOfService) => 0x001C,
            (QualityMajor::Uncertain, QualitySubstatus::LastUsableValue) => 0x0004,
            (QualityMajor::Uncertain, QualitySubstatus::SensorCalibrating) => 0x0010,
            (QualityMajor::Uncertain, QualitySubstatus::EguExceeded) => 0x0014,
            (QualityMajor::Uncertain, QualitySubstatus::SubNormal) => 0x0018,
            (QualityMajor::Good, QualitySubstatus::LocalOverride) => 0x0018,
            _ => 0x0000,
        };

        let raw = major_raw | substatus_raw | limit_raw;

        Self {
            major,
            substatus,
            limit,
            raw,
        }
    }

    /// Returns the major quality category.
    #[must_use]
    pub const fn major(&self) -> QualityMajor {
        self.major
    }

    /// Returns the specific substatus explanation.
    #[must_use]
    pub const fn substatus(&self) -> QualitySubstatus {
        self.substatus
    }

    /// Returns the limit condition flag.
    #[must_use]
    pub const fn limit(&self) -> QualityLimit {
        self.limit
    }

    /// Returns the original 16-bit raw quality word from the COM server.
    #[must_use]
    pub const fn raw(&self) -> u16 {
        self.raw
    }

    /// Standard Good quality (`0x00C0`).
    pub const GOOD: Self = Self {
        major: QualityMajor::Good,
        substatus: QualitySubstatus::NonSpecific,
        limit: QualityLimit::NotLimited,
        raw: 0x00C0,
    };

    /// Standard Bad quality (`0x0000`).
    pub const BAD: Self = Self {
        major: QualityMajor::Bad,
        substatus: QualitySubstatus::NonSpecific,
        limit: QualityLimit::NotLimited,
        raw: 0x0000,
    };

    /// Standard Uncertain quality (`0x0040`).
    pub const UNCERTAIN: Self = Self {
        major: QualityMajor::Uncertain,
        substatus: QualitySubstatus::NonSpecific,
        limit: QualityLimit::NotLimited,
        raw: 0x0040,
    };

    /// Bad quality due to configuration error (`0x0004`).
    pub const BAD_CONFIG_ERROR: Self = Self {
        major: QualityMajor::Bad,
        substatus: QualitySubstatus::ConfigurationError,
        limit: QualityLimit::NotLimited,
        raw: 0x0004,
    };

    /// Bad quality due to communication failure (`0x0018`).
    pub const BAD_COMM_FAILURE: Self = Self {
        major: QualityMajor::Bad,
        substatus: QualitySubstatus::CommFailure,
        limit: QualityLimit::NotLimited,
        raw: 0x0018,
    };

    /// Returns `true` if the major quality is `Good`.
    #[must_use]
    pub const fn is_good(&self) -> bool {
        matches!(self.major, QualityMajor::Good)
    }

    /// Returns `true` if the major quality is `Bad`.
    #[must_use]
    pub const fn is_bad(&self) -> bool {
        matches!(self.major, QualityMajor::Bad)
    }

    /// Returns `true` if the major quality is `Uncertain`.
    #[must_use]
    pub const fn is_uncertain(&self) -> bool {
        matches!(self.major, QualityMajor::Uncertain)
    }

    /// Returns `true` if the quality has active limits.
    #[must_use]
    pub const fn is_limited(&self) -> bool {
        !matches!(self.limit, QualityLimit::NotLimited)
    }
}

impl From<u16> for OpcQuality {
    fn from(raw: u16) -> Self {
        let major = match raw & 0x00C0 {
            0x00C0 => QualityMajor::Good,
            0x0040 => QualityMajor::Uncertain,
            _ => QualityMajor::Bad,
        };

        let limit = match raw & 0x0003 {
            0x0001 => QualityLimit::LowLimited,
            0x0002 => QualityLimit::HighLimited,
            0x0003 => QualityLimit::Constant,
            _ => QualityLimit::NotLimited,
        };

        let substatus_bits = raw & 0x003C;
        let substatus = match major {
            QualityMajor::Bad => match substatus_bits {
                0x0004 => QualitySubstatus::ConfigurationError,
                0x0008 => QualitySubstatus::NotConnected,
                0x000C => QualitySubstatus::DeviceFailure,
                0x0010 => QualitySubstatus::SensorFailure,
                0x0014 => QualitySubstatus::LastUsableValue,
                0x0018 => QualitySubstatus::CommFailure,
                0x001C => QualitySubstatus::OutOfService,
                _ => QualitySubstatus::NonSpecific,
            },
            QualityMajor::Uncertain => match substatus_bits {
                0x0004 => QualitySubstatus::LastUsableValue,
                0x0010 => QualitySubstatus::SensorCalibrating,
                0x0014 => QualitySubstatus::EguExceeded,
                0x0018 => QualitySubstatus::SubNormal,
                _ => QualitySubstatus::NonSpecific,
            },
            QualityMajor::Good => match substatus_bits {
                0x0018 => QualitySubstatus::LocalOverride,
                _ => QualitySubstatus::NonSpecific,
            },
        };

        Self {
            major,
            substatus,
            limit,
            raw,
        }
    }
}

impl From<OpcQuality> for u16 {
    #[inline]
    fn from(q: OpcQuality) -> Self {
        q.raw
    }
}

/// Error returned when parsing an invalid quality string.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseQualityError(pub String);

impl fmt::Display for ParseQualityError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Invalid OPC quality string: '{}'", self.0)
    }
}

impl std::error::Error for ParseQualityError {}

impl std::str::FromStr for OpcQuality {
    type Err = ParseQualityError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        if trimmed.eq_ignore_ascii_case("good") {
            Ok(Self::GOOD)
        } else if trimmed.eq_ignore_ascii_case("uncertain") {
            Ok(Self::UNCERTAIN)
        } else if trimmed.eq_ignore_ascii_case("bad") {
            Ok(Self::BAD)
        } else {
            Err(ParseQualityError(trimmed.to_string()))
        }
    }
}

impl fmt::Display for OpcQuality {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let major_str = match self.major {
            QualityMajor::Good => "Good",
            QualityMajor::Uncertain => "Uncertain",
            QualityMajor::Bad => "Bad",
        };

        let sub_str = match self.substatus {
            QualitySubstatus::NonSpecific => None,
            QualitySubstatus::ConfigurationError => Some("Configuration Error"),
            QualitySubstatus::NotConnected => Some("Not Connected"),
            QualitySubstatus::DeviceFailure => Some("Device Failure"),
            QualitySubstatus::SensorFailure => Some("Sensor Failure"),
            QualitySubstatus::CommFailure => Some("Comm Failure"),
            QualitySubstatus::OutOfService => Some("Out of Service"),
            QualitySubstatus::LastUsableValue => Some("Last Usable Value"),
            QualitySubstatus::SensorCalibrating => Some("Sensor Calibrating"),
            QualitySubstatus::EguExceeded => Some("EGU Exceeded"),
            QualitySubstatus::SubNormal => Some("Sub-Normal"),
            QualitySubstatus::LocalOverride => Some("Local Override"),
        };

        let limit_str = match self.limit {
            QualityLimit::NotLimited => None,
            QualityLimit::LowLimited => Some("Low Limited"),
            QualityLimit::HighLimited => Some("High Limited"),
            QualityLimit::Constant => Some("Constant"),
        };

        if f.width().is_none() {
            match (sub_str, limit_str) {
                (None, None) => write!(f, "{major_str}"),
                (Some(s), None) => write!(f, "{major_str} ({s})"),
                (None, Some(l)) => write!(f, "{major_str} [{l}]"),
                (Some(s), Some(l)) => write!(f, "{major_str} ({s}) [{l}]"),
            }
        } else {
            let formatted = match (sub_str, limit_str) {
                (None, None) => major_str.to_string(),
                (Some(s), None) => format!("{major_str} ({s})"),
                (None, Some(l)) => format!("{major_str} [{l}]"),
                (Some(s), Some(l)) => format!("{major_str} ({s}) [{l}]"),
            };
            f.pad(&formatted)
        }
    }
}
