[package]
name = "synch-polyfill"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Wendell Saligan <saliganw@gmail.com>"]
license = "MIT"
repository = "https://github.com/wends155/opc-cli"
description = "WaitOnAddress polyfill for Windows 7 / Server 2008 R2"

[lib]
name = "api_ms_win_core_synch_l1_2_0"
crate-type = ["cdylib", "rlib"]

[features]
default = []
std = []

[workspace]


[profile.release]
panic = "abort"

