// --------------------------------------------------------------------------
// PROVENANCE: Frozen OPC DA COM interface bindings
//
// Generated by `windows-bindgen` 0.62.1 from OPC Foundation IDL files
// (opcda.idl) via the rust_opc project.
//
// Upstream:  https://github.com/Ronbb/rust_opc
// Author:    Wang Ruobiao (© 2025, MIT License)
// Frozen:    2025 (vendored into opc-da-client, Phase 3)
//
// See THIRD_PARTY_LICENSES.md at the repository root for full license text.
// --------------------------------------------------------------------------
#![allow(warnings)]
#![allow(clippy::undocumented_unsafe_blocks)]

mod bindings;

pub use bindings::*;
